detect_ball:
  tuning_mode: false # Could set this here but leave it off so it can be easily set by the launch script
  x_min: 0
  x_max: 100
  y_min: 32
  y_max: 100
  h_min: 23
  h_max: 57
  s_min: 0
  s_max: 255
  v_min: 0
  v_max: 255
  sz_min: 0
  sz_max: 100
 
detect_ball_3d:
  h_fov: 1.089
  ball_radius: 0.033
  aspect_ratio: 1.333
  camera_frame: "front_cam_link_optical"